version: '3.3'

services:
  vsftpd:
    image: fauria/vsftpd
    volumes:
      - /Users/icetee/DEV/_test/:/home/vsftpd
    environment:
      - FTP_USER=user
      - FTP_PASS=pass
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    ports:
      - 127.0.0.1:20:20
      - 127.0.0.1:21:21
      - 127.0.0.1:21100-21110:21100-21110
    restart: always
